Name:           nwg-dock-hyprland
Version:        0.3.2
Release:        1
Summary:        Hyprland application dock
License:        MIT
Group:          NWG/Hyrpland
URL:            https://github.com/nwg-piotr/nwg-dock-hyprland
Source0:        https://github.com/nwg-piotr/nwg-dock-hyprland/archive/v%{version}/%{name}-%{version}.tar.gz
# Generated by running, inside the source tree:
# export GOPATH=$(pwd)/.godeps
# go mod download
# tar cJf ../../godeps-for-nwg-dock-hyprland-0.3.2.tar.xz .godeps
Source1:        godeps-for-nwg-dock-hyprland-0.3.2.tar.xz
BuildRequires:  golang
BuildRequires:  compiler(go-compiler)
BuildRequires:  zstd
BuildRequires:  pkgconfig(gtk-layer-shell-0)

%description
Configurable (w/ command line arguments and css) dock, written in Go, aimed
exclusively at the Hyprland Wayland compositor. It features pinned buttons,
client buttons and the launcher button.

%prep
%autosetup -p1 -a1

%build
#export GOPATH=$(pwd)/.godeps:$(pwd)/gopath
## Note build takes around 10 minutes, so be patient as there is no output!
go build \
   -mod=vendor \
   -buildmode=pie

%install
install -d -m 0755 %{buildroot}%{_bindir} %{buildroot}%{_datadir}/%{name}
install -m 0755 %{name} %{buildroot}%{_bindir}/%{name}
install -m 0644 config/style.css %{buildroot}%{_datadir}/%{name}/style.css

%files
%license LICENSE
%{_bindir}/%{name}
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/style.css
